# syntax=docker/dockerfile:1
FROM python:3.9
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY requirements.txt /code/requirements.txt
COPY start_dev.sh /code/
EXPOSE 8000
RUN chmod 755 /code/start_dev.sh
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y nodejs \
    npm
RUN pip install -r /code/requirements.txt
RUN pip install django-cors-headers
ENV VCP_BACKEND_SERVER=DEV
COPY . /code/