version: '3.7'

services:

  frontend:
    container_name: VCPFrontend
    build: 
      dockerfile: Dockerfile
    volumes:
      - ./src:/VCPFrontend/src
      - '/VCPFrontend/node_modules'
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true